# Job name
name: Application linting

# When the to run the greeting
on: [pull_request]

# Jobs to run for the action (You can have multiple actions in one file)
jobs:
  run-linters:
    # Job display name
    name: Linting Action

    # Runs on a Linux based OS
    runs-on: ubuntu-latest

    # Steps involved for this particular task
    steps:
      # Checks out the repository and enables the use of commands made available in the project ie pnpm run
      - name: Checkout Git repository
        uses: actions/checkout@v4

      # Configure Node.js and pnpm
      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      # Cache the node_modules, only invalidate when the pnpm-lock.yaml changes
      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      # Cache Turbo build artifacts
      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      # Installs all the project dependencies e.g. prettier, eslint etc via pnpm
      - name: Install pnpm dependencies
        run: 'pnpm install --frozen-lockfile'

      # Run linting using Turbo
      - name: Run linting
        run: 'pnpm lint'

      # Run prettier formatting check using Turbo
      - name: Run prettier check
        run: 'pnpm prettier'

      # Run type checking using Turbo
      - name: Run type checking
        run: 'pnpm check-types'
