# Job name
name: Application linting

# When the to run the greeting
on: [pull_request]

# Jobs to run for the action (You can have multiple actions in one file)
jobs:
  run-linters:
    # Job display name
    name: Linting Action

    # Runs on a Linux based OS
    runs-on: ubuntu-latest

    # Steps involved for this particular task
    steps:
      # Checks out the repository and enables the use of commands made available in the project ie npm run
      - name: Checkout Git repository
        uses: actions/checkout@v2

      # Configure yarn
      - name: Setup Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      # Installs all the project dependencies e.g. prettier, eslint etc via a custom project script
      - name: Install yarn dependencies
        run: 'yarn'

      # Run the linting action
      - name: Run linters
        uses: samuelmeuli/lint-action@v1.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Authorizes the github action via a Github token which is for this repo only (Generated automatically)
          eslint: true # Enables eslint
          prettier: true # Enables prettier to prettieifer the code when commiting and spots any violations
          auto_fix: false # Auto fixes an prettier or eslint violations
