# Job name
name: Application testing

# When the to run the greeting
on: [pull_request]

# Jobs to run for the action (You can have multiple actions in one file)
jobs:
  test:
    # Job display name
    name: Running React-Testing-Library and Jest tests

    # Runs on a Linux based OS
    runs-on: ubuntu-latest

    # Steps involved for this particular task
    steps:
      # Checks out the repository and enables the use of commands made available in the project ie npm run
      - name: Checkout Git repository
        uses: actions/checkout@v2

      # Configure yarn
      - name: Setup Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      # Installs all the project dependencies e.g. prettier, eslint etc via a custom project script
      - name: Install Node.js dependencies
        run: 'yarn'

      # Run the react-testing-library tests
      - name: Run all tests
        run: 'yarn client:test'
